Fix hardhat artifacts collection
Consensys/diligence-fuzzing pull request #85
Opened 2024-04-15 06:06 UTC by Nurchik

* Ignore library contracts by default

2024-04-15 19:44 UTC, cd1m0 requested changes
Good work! Some small nits requested.

I think this will work as a patch over. But eventually we need to re-think the information we send to the FaaS API.

In a perfect world, I just want to send a list of build artifacts `B`, and a mapping `M` from deployed contract addresses to a tuple `[idx, srcFile, contractName]`. Then for each deployed contract, the ast information is in `B[idx][srcFile][contractName]["ast"]`. 

In the FaaS backend, we can create a separate solc-typed-ast for each entry `B[i]`, and we can be sure that the `id`s are unique. 

However this is a longer discussion, that needs to involve more people (@wuestholz, @JoranHonig).

2024-04-15 19:44 UTC, cd1m0 commented on fuzzing_cli/fuzz/ide/hardhat.py
> +        for source_file_name, contracts in self.build_info.items():
Can we add code here that:

1. Detects if the same `source_file_name` appears in multiple build_info files
2. Communicates a warning/error to the FaaS API when this happens

I want to be able to detect when this happens in practice so we can debug it and adapt the code

2024-04-18 11:53 UTC, Nurchik commented on fuzzing_cli/fuzz/ide/generic.py
> +            # if contract is not found in the mapping, we assume it's a contract
it shouldn't happen, but it's an additional safe measure

2024-04-23 00:46 UTC, cd1m0 approved these changes
lgtm

2024-04-23 05:44 UTC, merged